#!/bin/sh

set -e

test $DEBIAN_SCRIPT_DEBUG && set -v -x

chperms() {
        # chperms <user> <group> <perms> <file>
        if ! OVERRIDE=`dpkg-statoverride --list $4 2>&1`; then
                if [ -e $4 ]; then
                        chown $1:$2 $4
                        chmod $3 $4
                fi
        fi
}

case "$1" in
  configure)
    if ! getent passwd media > /dev/null; then
        adduser --quiet \
                --system \
                --group \
                --no-create-home \
                --home /home/media \
                media
    fi

    chperms media media 4775 /opt/Radarr

    chperms media media 4775 /home/media/.config/Radarr
    
    
    # Set permissions on data directory (always do this instead only on creation in case user was changed via dpkg-reconfigure)
chown -R media:media /home/media/.config/Radarr


# Set permissions on /opt/Radarr
chown -R media:media /opt/Radarr
# update database
    ;;
esac
# Automatically added by dh_systemd_enable/12.10ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'radarr.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'radarr.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'radarr.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'radarr.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/12.10ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		deb-systemd-invoke $_dh_action 'radarr.service' >/dev/null || true
	fi
fi
# End automatically added section


exit 0
