#!/bin/bash
# Socat-Script Port 8080
#Don't forget to make this Script executable!!! Use chmod 755
# TCP Port 8080
sudo socat tcp-listen:8080,fork,reuseaddr exec:'ip netns exec protected socat STDIO tcp-connect\:127.0.0.1\:8080',nofork
